markdown: redcloth
pygments: true
plugins: ./_plugins

title: Liurongxing
url: http://www.liurongxing.cn
feed: /atom.xml
author:
    name: LiuRongxing
    email: lrx512@gmail.com
    twitter: twitter.com/javasboy
description: 这是LiuRongxing的又一个博客，它是基于 Jekyll 搭建起来的。在这里，不仅仅是用来快速记录工作，学习，生活的一点一滴的地方，更是 LiuRongxing 对 Jekyll 的学习和使用的一次有意义的实践。
